[package]
name = "wasm-hello-world"
version = "0.1.0"
authors = ["hidarikani <19387605+hidarikani@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
